CREATE TABLE hep (
    run                 INTEGER,
    luminosityBlock     BIGINT,
    event               BIGINT,

    MET_pt              FLOAT,
    MET_phi             FLOAT,
    MET_sumet           FLOAT,
    MET_significance    FLOAT,
    MET_CovXX           FLOAT,
    MET_CovXY           FLOAT,
    MET_CovYY           FLOAT,

    HLT_IsoMu24_eta2p1                  BOOLEAN,
    HLT_IsoMu24                         BOOLEAN,
    HLT_IsoMu17_eta2p1_LooseIsoPFTau20  BOOLEAN,

    PV_npvs            INTEGER,
    PV_x               FLOAT,
    PV_y               FLOAT,
    PV_z               FLOAT,
    
    Muon_pt              ARRAY<FLOAT>,
    Muon_eta             ARRAY<FLOAT>,
    Muon_phi             ARRAY<FLOAT>,
    Muon_mass            ARRAY<FLOAT>,
    Muon_charge          ARRAY<INTEGER>,
    Muon_pfRelIso03_all  ARRAY<FLOAT>,
    Muon_pfRelIso04_all  ARRAY<FLOAT>,
    Muon_tightId         ARRAY<BOOLEAN>,
    Muon_softId          ARRAY<BOOLEAN>,
    Muon_dxy             ARRAY<FLOAT>,
    Muon_dxyErr          ARRAY<FLOAT>,
    Muon_dz              ARRAY<FLOAT>,
    Muon_dzErr           ARRAY<FLOAT>,
    Muon_jetIdx          ARRAY<INTEGER>,
    Muon_genPartIdx      ARRAY<INTEGER>,

    Electron_pt              ARRAY<FLOAT>,
    Electron_eta             ARRAY<FLOAT>,
    Electron_phi             ARRAY<FLOAT>,
    Electron_mass            ARRAY<FLOAT>,
    Electron_charge          ARRAY<INTEGER>,
    Electron_pfRelIso03_all  ARRAY<FLOAT>,
    Electron_dxy             ARRAY<FLOAT>,
    Electron_dxyErr          ARRAY<FLOAT>,
    Electron_dz              ARRAY<FLOAT>,
    Electron_dzErr           ARRAY<FLOAT>,
    Electron_cutBasedId      ARRAY<BOOLEAN>,
    Electron_pfId            ARRAY<BOOLEAN>,
    Electron_jetIdx          ARRAY<INTEGER>,
    Electron_genPartIdx      ARRAY<INTEGER>,

    Photon_pt              ARRAY<FLOAT>,
    Photon_eta             ARRAY<FLOAT>,
    Photon_phi             ARRAY<FLOAT>,
    Photon_mass            ARRAY<FLOAT>,
    Photon_charge          ARRAY<INTEGER>,
    Photon_pfRelIso03_all  ARRAY<FLOAT>,
    Photon_jetIdx          ARRAY<INTEGER>,
    Photon_genPartIdx      ARRAY<INTEGER>,

    Jet_pt              ARRAY<FLOAT>,
    Jet_eta             ARRAY<FLOAT>,
    Jet_phi             ARRAY<FLOAT>,
    Jet_mass            ARRAY<FLOAT>,
    Jet_puId            ARRAY<BOOLEAN>,
    Jet_btag            ARRAY<FLOAT>,

    Tau_pt              ARRAY<FLOAT>,
    Tau_eta             ARRAY<FLOAT>,
    Tau_phi             ARRAY<FLOAT>,
    Tau_mass            ARRAY<FLOAT>,
    Tau_charge          ARRAY<INTEGER>,
    Tau_decayMode       ARRAY<INTEGER>,
    Tau_relIso_all      ARRAY<FLOAT>,
    Tau_jetIdx          ARRAY<INTEGER>,
    Tau_genPartIdx      ARRAY<INTEGER>,
    Tau_idDecayMode     ARRAY<BOOLEAN>,
    Tau_idIsoRaw        ARRAY<FLOAT>,
    Tau_idIsoVLoose     ARRAY<BOOLEAN>,
    Tau_idIsoLoose      ARRAY<BOOLEAN>,
    Tau_idIsoMedium     ARRAY<BOOLEAN>,
    Tau_idIsoTight      ARRAY<BOOLEAN>,
    Tau_idAntiEleLoose  ARRAY<BOOLEAN>,
    Tau_idAntiEleMedium ARRAY<BOOLEAN>,
    Tau_idAntiEleTight  ARRAY<BOOLEAN>,
    Tau_idAntiMuLoose   ARRAY<BOOLEAN>,
    Tau_idAntiMuMedium  ARRAY<BOOLEAN>,
    Tau_idAntiMuTight   ARRAY<BOOLEAN>

) USING PARQUET LOCATION '/users/noobjc/iceberg-spark-hep/dataset';
